#!/usr/bin/env zsh

# -------------------------------------------------------------	#
#  Usage Instructions                                           #
#  Run this script: chmod +x ./slay && ./slay                   #
# -------------------------------------------------------------	#

SLAY_DIR="$(cd "$(dirname "$0")" && pwd)" # Get full directory name of this script

# TWIRL & SWAG: load utility functions persistently
# -------------------------------------------------------------
source $SLAY_DIR/twirl > /dev/null
source $SLAY_DIR/swag > /dev/null

# STEP: Prerequisites
# -------------------------------------------------------------
do_system() {
	source $SLAY_DIR/steps/system
}

# STEP: Prerequisites
# -------------------------------------------------------------
do_deps() {
	source $SLAY_DIR/steps/deps
}

# STEP: Set macOS preferences
# -------------------------------------------------------------
do_macos() {
	need_restart=y;
	source $SLAY_DIR/steps/macos
}

# STEP: Install NVM & Node
# -------------------------------------------------------------
do_node() {
	source $SLAY_DIR/steps/node
}

# STEP: Install apps via Homebrew
# -------------------------------------------------------------
do_homebrew() {
	source $SLAY_DIR/steps/brew
}

# STEP: Hot Sauce
# -------------------------------------------------------------
add_hotsauce() {
	source $SLAY_DIR/steps/hotsauce
}

# DISPLAY: Notifications
# -------------------------------------------------------------
show_notices() {
	if [[ $need_restart = y ]]; then
		echo ""
		print_message "Reboot your machine for all changes to take effect." emphasize
		# Prompt user
		printf "\n${INDENT}${PURPLE}Do you want to REBOOT? ${RESET}(y/N)"

		# Read a single key from the user
		read -s -k 1 key
		echo ""  # Move to a new line for better readability

		# Check the user's input
		if [[ "$key" == "y" || "$key" == "Y" ]]; then
			echo "${INDENT}Rebooting…\n"
			# sudo reboot
		else
			echo "${INDENT}Reboot cancelled.\n"
			exit 0
		fi
	fi
}

# STEP: Errthang
# -------------------------------------------------------------
do_errthang() {
	do_system;
	do_deps;
	do_macos;
	do_node;
	do_homebrew;
	add_hotsauce;
}

# STEP: Exit
# -------------------------------------------------------------
do_nothing() {
	echo -e "\n${INDENT} ✨ Did nothing ✨";
	exit 0;
}

# notices
# -------------------------------------------------------------
cleanup() {
	local exit_code=$?
	if [ $exit_code -ne 0 ]; then
		print_message "" blank
		print_message "Formation failed! Please check logs." fail
	else
		congrats
		show_notices
	fi
	exit $exit_code
}

# DISPLAY: help menu
# -------------------------------------------------------------
show_help() {
	echo ""
	echo "   Usage: ./slay [OPTION]"
	echo "   Available options:"
	echo "   -h, --help      Show this message"
	echo "   -a, --all       Setup everything"
	echo "   -u, --update    Update macOS"
	echo "   -i, --install   Install software"
	echo "   -s, --hotsauce  Add hot sauce"
}

# DISPLAY: menu options
# -------------------------------------------------------------
show_menu() {
	echo -e "${INDENT} ${BOLD}${UNDERLINE}Select options:${RESET}"

	echo -en "${RESET}${INDENT} Setup Everything? (y/n): ${PURPLE}"
	read -r setup_all

	if [[ $setup_all == "y" ]]; then
		do_errthang
		return
	fi

	echo -en "${RESET}${INDENT} Update macOS? (y/n): ${PURPLE}"
	read -r update_macos

	echo -en "${RESET}${INDENT} Configure macOS? (y/n): ${PURPLE}"
	read -r configure_macos

	echo -en "${RESET}${INDENT} Install NVM/Node? (y/n): ${PURPLE}"
	read -r install_node

	echo -en "${RESET}${INDENT} Install Packages? (y/n): ${PURPLE}"
	read -r install_packages

	echo -en "${RESET}${INDENT} Add Hot Sauce? (y/n): ${PURPLE}"
	read -r add_hotsauce

	if [[ $update_macos == "y" || $configure_macos == "y" || $install_node == "y" || $install_packages == "y" || $add_hotsauce == "y" ]]; then
		do_system
	fi

	[[ $update_macos == "y" ]] && do_deps
	[[ $configure_macos == "y" ]] && do_macos
	[[ $install_node == "y" ]] && do_node
	[[ $install_packages == "y" ]] && do_homebrew
	[[ $add_hotsauce == "y" ]] && add_hotsauce
}

slay() {
	local command="$1"
	local skip_welcome=false

	# If the second parameter is "--skip", set skip_welcome to true
	if [[ "$2" == "--skip" ]]; then
		skip_welcome=true
	fi

	# Show welcome if no command provided
	if [[ -z "$command" ]] && [[ "$skip_welcome" == false ]]; then
		show_welcome
	fi

	case "$command" in
		-h | --help | h | help) show_help; exit 0 ;;
		-a | --all | a | all) [[ "$skip_welcome" == false ]] && show_welcome; do_errthang ;;
		-u | --update | u | update) [[ "$skip_welcome" == false ]] && show_welcome; do_system; do_deps ;;
		-i | --install | i | install) [[ "$skip_welcome" == false ]] && show_welcome; do_system; do_homebrew ;;
		-s | --hotsauce | s | hotsauce) [[ "$skip_welcome" == false ]] && show_welcome; do_system; add_hotsauce ;;
		*) show_menu ;;
	esac
}

# welcome: http://patorjk.com/software/taag/ (font: Script)
# -------------------------------------------------------------
show_welcome() {
	echo -n $PURPLE
	echo "
 _
| |                                🍋
| |  __   ,_    _  _  _    __, _|_     __   _  _
|/  /  \_/  |  / |/ |/ |  /  |  |  |  /  \_/ |/ |
|__/\__/    |_/  |  |  |_/\_/|_/|_/|_/\__/   |  |
|\/
|/  ${ITALIC}${UNDERLINE}cause you slay${RESET}.       ${DIM}made by mina for macos${RESET}.
"
	echo -n $RESET

	# Prompt user for actions to take
	echo "${INDENT} Okay $(whoami) now let's get in formation.\n"
	echo "${INDENT} Safe to run multiple times on the same machine."
	echo "${INDENT} It installs, upgrades, or skips packages based"
	echo "${INDENT} on what is already installed on the machine."
	echo $LINE_SEPARATOR
}

# 🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋
# -------------------------------------------------------------
congrats() {
	echo "${RESET}${INDENT}${DIM}─────────────────────────────────────────────────────${RESET}\n"
	print_message "${BOLD}Congrats! You're in formation! 🍋${RESET}" success

	printf "  ╭────────────────────────────────────────────────────╮
  │ Thanks for using Formation!                        │
  │ If you liked it, then you should put a star on it! │
  │                                                    │
  │ ${UNDERLINE}https://github.com/minamarkham/formation${RESET}           │
  ╰────────────────────────────────────────────────────╯
"

}

# cuz you slay <== this is the main command
# -------------------------------------------------------------
slay "$@"

# clean up
# -------------------------------------------------------------
trap cleanup EXIT # Set trap to run cleanup when the script exits
